apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fleet-nginx
  name: fleet-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fleet-nginx
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - sleep inf
        image: busybox
        name: busybox
---
apiVersion: v1
data:
  key1: item1
  key2: item2
  key3: 
    - item3a
    - item3b
kind: ConfigMap
metadata:
  name: testing-map
