apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-helm-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-helm-repo
  template:
    metadata:
      labels:
        app: nginx-helm-repo
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
            - name: auth
              mountPath: /etc/nginx/conf.d/auth
            - name: data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: auth
          secret:
            secretName: nginx-auth
        - name: config
          configMap:
            name: nginx-config
        - name: data
          configMap:
            name: helm-repo-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      location / {
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/conf.d/auth/htpasswd;
        root /usr/share/nginx/html;
        index index.yaml;
        autoindex on;
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-auth
type: Opaque
data:
  htpasswd: dXNlcjokYXByMSR4Tm1CVVFxVCRtWGJNazFGN0NFNmN1U01jWjVzY0gw # user:password
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-helm-repo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-repo-data
data:
  index.yaml: |
    apiVersion: v1
    entries:
      app:
        - name: app
          version: 0.1.0
          urls:
            - http://nginx-service.default.svc.cluster.local:80/app-0.1.0.tgz
binaryData:
  app-0.1.0.tgz: H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxtAOyVsWrDMBCGPesp7gXinBxHAW8lS6G0Q4fuV/vSilrOYSmBEvLuRSkJOEMztE4o6Fskn43t4/7/F4lMl+/Uh/yTXJuNAiKiKcvDiojnK+pylunSFNqY2SLWtV7MywxwnN8ZsvGB+gx//a3z5v4JJPaFe2/XXQXbQpHI6RJznaNq2Ne9lXAo3cE9tw7qKBhYrXt42Lxy33FgrzpyXAGJqO3wDbduMfED0f9bajfsxwuAS/6P+6H/iwKL5P9rEOcf2ElLgf20Xncr++ZI/lQMF/PfzM/mXxqDaf7XYJD/Wn3YrqlgeZDBI4lyHKihQJUC+A743Q7yZ26ZPOdP5Bj2+8lJNur4rCcnLU9qVx238c7Edt42nE6ERCKRuD1fAQAA//9ZTKl3AA4AAA==
